### ISSUE TITLE
Unknown error occurred - can not connect to device

### ISSUE THREAD

**Issue by Mip2016** [powerpaul17/maxcul#8]
After installation via HACS I added the integration and during Serial setup my Cul stick from Busware was proposed. I selected the stick. Got first error.

I tried with manual path - I got the second error.

other sticks (zigbee, zwave, lacrosse) are working fine - except this integration with culstick

**Comment by Speed-xD** [comment]
Could this also solve your problem:
https://github.com/powerpaul17/maxcul/issues/7#issuecomment-2409283650

**Comment by Mip2016** [comment]
(1) I checked the comment of @Speed-xD without success. (2) I checked it with "self._baudrate = 9600" as I used the stick previously with FHEM at 9600. I checked the log >

RuntimeError: Caught blocking call to sleep with args (2,) inside the event loop by custom integration 'maxcul' at custom_components/maxcul/config_flow.py, line 185: time.sleep(2). (offender: /config/custom_components/maxcul/config_flow.py, line 185: time.sleep(2)), please create a bug report at https://github.com/powerpaul17/maxcul/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep




AND 


Logger: homeassistant.util.loop
Quelle: util/loop.py:136
Erstmals aufgetreten: 16:21:49 (1 Vorkommnisse)
Zuletzt protokolliert: 16:21:49

Detected blocking call to sleep with args (2,) inside the event loop by custom integration 'maxcul' at custom_components/maxcul/config_flow.py, line 185: time.sleep(2) (offender: /config/custom_components/maxcul/config_flow.py, line 185: time.sleep(2)), please create a bug report at https://github.com/powerpaul17/maxcul/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle return await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/maxcul/config_flow.py", line 88, in async_step_device_picker if await test_connection(device_path): File "/config/custom_components/maxcul/config_flow.py", line 177, in test_connection return get_cul_version(com_port) File "/config/custom_components/maxcul/config_flow.py", line 185, in get_cul_version time.sleep(2)

**Comment by systemofapwne** [comment]
I also encountered this issue (and some more, that are related). In short: Running blocking functions like time.sleep in the async eventloop is discouraged. One should use `await asyncio.sleep()` instead. The corresponding error message is
```
RuntimeError: Caught blocking call to sleep with args (2,) inside the event loop by custom integration 'maxcul' at custom_components/maxcul/config_flow.py, line 185: time.sleep(2). (offender: /config/custom_components/maxcul/config_flow.py, line 185: time.sleep(2)), please create a bug report at https://github.com/powerpaul17/maxcul/issues
```
After quickly fixing the two offending lines, more async related warnings popped up, which need to be addressed: 
```
WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'maxcul' calls async_forward_entry_setup for integration, maxcul with title: <REDACTED>:2323 and entry_id: <REDACTED>, which is deprecated, await async_forward_entry_setups instead at custom_components/maxcul/__init__.py, line 95: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/powerpaul17/maxcul/issues#033
```

I think, the fixes are rather trivial. I plan to work on this tonight. Expect a PR.
